name: Test 78 # Related to https://stackoverflow.com/questions/75720251/setup-environment-to-use-variable-context-when-calling-a-reusable-workflow

on:
  push:
    branches:
      - main  
jobs:
  - name: generate secret
    id: generate-secret
    shell: bash
    run: |
      GENERATED_SECRET=$((RANDOM))
      echo "::add-mask::$GENERATED_SECRET"
      SECRET_HANDLE=$(secret-store store-secret "$GENERATED_SECRET")
      echo "handle=$SECRET_HANDLE" >> "$GITHUB_OUTPUT"